name = "Dear Diary"
license = "MIT"
licenselink = "https://github.com/InkStash/dear-diary/blob/main/LICENSE"
description = "A blog of one's own."
homepage = "https://github.com/InkStash/dear-diary/"
tags = ["blog"]
features = ["mobile","elegant"]
min_version = "0.59.0"

[author]
  name = "Ink Stash"
  homepage = "https://github.com/InkStash/"


# If porting an existing theme
[original]
  name = "amazingrise"
  homepage = "https://amazingrise.net/"
  repo = "https://github.com/amazingrise/hugo-theme-diary/"
